name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  tf: 
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v1

      - name: Terraform Init
        uses: hashicorp/setup-terraform@v3
        env:
          TF_ACTION_WORKING_DIR: 'infrastructure'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }} 

